### ISSUE TITLE
php pages not found

### ISSUE THREAD

**Issue by lupa95** [opnsense/ui_devtools#4]
Hi, 

i've set up the dev tools environment with phalcon 3.4 and php 7.1. 
The server seems to be running fine but no php page from the www subdir gets rendered. (e.g. http://localhost:8000/index.php) I always get a "Page not found" error trying to access them. The dynamically created views from Volt templates work fine though (e.g. http://localhost:8000/ui/firewall/alias).

Any ideas what might be wrong with my installation? I can't seem to find the issue...

Thanks!

**Comment by AdSchellevis** [comment]
Only new (mvc) style modules are supported, so only /ui and /api endpoints are expected to work
